### ISSUE TITLE
bug in sec and min conversion

### ISSUE THREAD

**Issue by isramos** [msparks/arduino-ds1302#3] opened 2013-05-25 22:47 UTC
I modified the sample sketch to run every one sec. There's a bug where every other sec and every other minute is wrong. See attached image.

![ds1302 bug matt sparks](https://f.cloud.github.com/assets/112402/564664/e132f6fa-c58c-11e2-9845-99a5cdec3d5b.png)

**Comment by msparks** [comment] 2015-01-03 10:17
I received the DS1302 from dx.com, linked by @otmezger above. Alas, I was still not able to reproduce the issue observed here with my Arduino Uno, nor with my "Pro Micro" Arduino clone. I looked at the serial communication with a logic analyzer (a Saelae Logic8) and wasn't able to find any timing issues that I had previously theorized. The clock cycles are much slower than they have to be to meet the datasheet spec.

However, I just pushed a number of changes to the library, most notably:

* Burst mode reads and writes for time
* Support for RAM reads and writes

I'm hoping that the burst mode for retrieving the time will magically fix the problem here. @otmezger, @andrewrapp, @JAnwyl, @isramos: if you get a chance, would you please pull and try the examples in the updated library and see if they work as expected?

**Comment by ManuTester** [comment] 2016-12-13 02:35
I had the same problem. I looked at the otmezger code and even reworked the writeOut code to use a loop and have a "release" paramter so that it puts the IO pin in INPUT mode BEFORE setting the CLK low (that's when the DS1302 starts driving the pin, so without this fix, they work against each other for a short period of time...)
Anyway nothing helped, EXCEPT putting a pullup resistor on the IO line. After reading the datasheet I found out that the DS1302 only outputs 2.4V as high signal even when powered with 5V. Thats a little bit too low for the arduino. The pullup seems to help to get the last missing millivolts :)

Then I changed in the code DS1302.cpp line 113
pinMode(io_pin_, INPUT);
to
pinMode(io_pin_, INPUT_PULLUP);

Now kind of works without external pullup,
But I don't like the "solution" so I will change the design to use an arduino with 3.3V and run the DS1302 at 3.3V also. I only need a level shifter for the led matrix display then.

**Comment by ammar1998** [comment] 2017-06-28 22:19
I had same problem. After that I can fix this problem you must be connect crystal body to ground Or touch it after it is worked!!!
Try this. 
Sorry about my language.

**Comment by burak1000** [comment] 2017-09-19 18:01
I had same problem. it problem because of the supply voltage. if you supply ds1302 with 3.3V and if your crystal is bad quality, this  happening.
Result: supply with 5V your DS1302.

**Comment by msparks** [comment] 2018-03-18 23:14
Might be fixed by #8. Please reopen if not.

**Closed by msparks** 2018-03-18 23:14 UTC
